name: 'Goimports'
author: 'Jérôme Pogeant'
description: 'Check imports of your code using goimports'
inputs:
  goimports-path:
    description: 'Path used by goimports command'
    required: false
    default: './'
outputs:
  goimports-output:
    description: 'The goimports output if the command fail'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.goimports-path }}
branding:
  icon: 'check-circle'
  color: 'green'
